-- MySQL Script generated by MySQL Workbench
-- 05/18/17 08:33:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`flats_rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flats_rent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flats_rent` (
  `obj_id` INT(30) NOT NULL AUTO_INCREMENT,
  `user_id` INT(30) NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(5) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` TEXT(300) NULL,
  `obj_price` INT(30) NULL,
  `obj_floor` INT(3) NULL,
  `obj_floors_num` INT(3) NULL,
  `obj_rooms_num` INT(3) NULL,
  `obj_year_build` DATE NULL,
  `obj_sq_common` INT(10) NULL,
  `obj_sq_living` INT(10) NULL,
  `obj_sq_kitchen` INT(10) NULL,
  `obj_status` VARCHAR(10) NULL,
  `obj_from` VARCHAR(10) NULL,
  `obj_reservation` TINYINT(1) NULL,
  `map_coord_x` VARCHAR(45) NULL,
  `map_coord_y` VARCHAR(45) NULL,
  `date` DATE NULL,
  `fac_aircond` TINYINT(1) NULL,
  `fac_dishwasher` TINYINT(1) NULL,
  `fac_fridge` TINYINT(1) NULL,
  `fac_furniture` TINYINT(1) NULL,
  `fac_microwave` TINYINT(1) NULL,
  `fac_tel` TINYINT(1) NULL,
  `fac_tv` TINYINT(1) NULL,
  `fac_washer` TINYINT(1) NULL,
  `fac_wifi` TINYINT(1) NULL,
  `rent_time` VARCHAR(45) NULL,
  `obj_guests_num` INT(4) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`houses_rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`houses_rent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`houses_rent` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(4) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `obj_price` INT NULL,
  `obj_floors_num` INT NULL,
  `obj_rooms_num` INT NULL,
  `obj_year_build` DATE NULL,
  `obj_sq_common` INT NULL,
  `obj_sq_living` INT NULL,
  `obj_sq_kitchen` INT NULL,
  `obj_status` VARCHAR(45) NULL,
  `obj_from` VARCHAR(45) NULL,
  `obj_reservation` VARCHAR(45) NULL,
  `map_coord_x` VARCHAR(45) NULL,
  `map_coord_y` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `rent_time` VARCHAR(45) NULL,
  `fac_aircond` VARCHAR(45) NULL,
  `fac_dishwasher` VARCHAR(45) NULL,
  `fac_fridge` VARCHAR(45) NULL,
  `fac_furniture` VARCHAR(45) NULL,
  `fac_microwave` VARCHAR(45) NULL,
  `fac_tel` VARCHAR(45) NULL,
  `fac_tv` VARCHAR(45) NULL,
  `fac_washer` VARCHAR(45) NULL,
  `fac_wifi` VARCHAR(45) NULL,
  `obj_guests_num` VARCHAR(45) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flats_sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`flats_sell` ;

CREATE TABLE IF NOT EXISTS `mydb`.`flats_sell` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(6) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `obj_price` INT NULL,
  `obj_floor` INT NULL,
  `obj_floors_num` VARCHAR(45) NULL,
  `obj_rooms_num` INT NULL,
  `obj_year_build` DATE NULL,
  `obj_sq_common` INT NULL,
  `obj_sq_living` INT NULL,
  `obj_sq_kitchen` INT NULL,
  `obj_status` VARCHAR(45) NULL,
  `obj_from` VARCHAR(45) NULL,
  `map_coord_x` VARCHAR(45) NULL,
  `map_coord_y` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_login` VARCHAR(100) NULL,
  `user_password` VARCHAR(100) NULL,
  `user_status` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_info` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_s_name` VARCHAR(45) NULL,
  `user_tel_num` VARCHAR(45) NULL,
  `user_email` VARCHAR(60) NULL,
  `user_rank` VARCHAR(45) NULL,
  `users_user_id` INT NOT NULL,
  `users_flats_sell_flat_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `users_user_id`, `users_flats_sell_flat_id`),
  INDEX `fk_user_info_users1_idx` (`users_user_id` ASC, `users_flats_sell_flat_id` ASC),
  CONSTRAINT `fk_user_info_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`images` ;

CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `obj_id` INT NULL,
  `e_type` VARCHAR(45) NULL,
  `path` VARCHAR(100) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reservations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reservations` (
  `reservation_id` INT NOT NULL,
  `estate_id` INT NULL,
  `status` VARCHAR(45) NULL,
  `date_from` DATE NULL,
  `date_to` DATE NULL,
  `total_price` INT NULL,
  `agensy_fees` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ground_rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ground_rent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ground_rent` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `obj_size` VARCHAR(45) NULL,
  `obj_price` INT NULL,
  `obj_status` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commercial_rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commercial_rent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commercial_rent` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(45) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` TEXT(400) NULL,
  `obj_square` VARCHAR(45) NULL,
  `obj_price_per_meter` VARCHAR(45) NULL,
  `obj_status` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `sep_entrance` TINYINT(1) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`houses_sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`houses_sell` ;

CREATE TABLE IF NOT EXISTS `mydb`.`houses_sell` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(45) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `obj_price` VARCHAR(45) NULL,
  `obj_floors_num` VARCHAR(45) NULL,
  `obj_rooms_num` VARCHAR(45) NULL,
  `obj_year_build` VARCHAR(45) NULL,
  `obj_sq_common` VARCHAR(45) NULL,
  `obj_sq_living` VARCHAR(45) NULL,
  `obj_sq_kitchen` VARCHAR(45) NULL,
  `obj_status` VARCHAR(45) NULL,
  `obj_from` VARCHAR(45) NULL,
  `map_coord_x` VARCHAR(45) NULL,
  `map_coord_y` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commercial_sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commercial_sell` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commercial_sell` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(45) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `obj_square` VARCHAR(45) NULL,
  `obj_price_per_meter` VARCHAR(45) NULL,
  `obj_status` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `sep_entrance` VARCHAR(45) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ground_sell`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ground_sell` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ground_sell` (
  `obj_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `obj_size` VARCHAR(45) NULL,
  `obj_price` VARCHAR(45) NULL,
  `obj_status` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;