INSERT INTO `mydb`.`images_ground_sell`
(`image_id`,`obj_id`,`path`,`status`)
VALUES
(NULL,1,'/static/img/grounds/g1.jpg','main'),
(NULL,1,'/static/img/grounds/g2.jpg','secondary'),
(NULL,1,'/static/img/grounds/g3.jpg','secondary'),
(NULL,1,'/static/img/grounds/g4.jpg','secondary'),
(NULL,1,'/static/img/grounds/g5.jpg','secondary'),
(NULL,1,'/static/img/grounds/g6.jpg','secondary'),

(NULL,2,'/static/img/grounds/g2.jpg','main'),
(NULL,2,'/static/img/grounds/g1.jpg','secondary'),
(NULL,2,'/static/img/grounds/g3.jpg','secondary'),
(NULL,2,'/static/img/grounds/g4.jpg','secondary'),
(NULL,2,'/static/img/grounds/g5.jpg','secondary'),
(NULL,2,'/static/img/grounds/g6.jpg','secondary'),

(NULL,3,'/static/img/grounds/g3.jpg','main'),
(NULL,3,'/static/img/grounds/g2.jpg','secondary'),
(NULL,3,'/static/img/grounds/g1.jpg','secondary'),
(NULL,3,'/static/img/grounds/g4.jpg','secondary'),
(NULL,3,'/static/img/grounds/g5.jpg','secondary'),
(NULL,3,'/static/img/grounds/g6.jpg','secondary'),

(NULL,4,'/static/img/grounds/g4.jpg','main'),
(NULL,4,'/static/img/grounds/g2.jpg','secondary'),
(NULL,4,'/static/img/grounds/g3.jpg','secondary'),
(NULL,4,'/static/img/grounds/g1.jpg','secondary'),
(NULL,4,'/static/img/grounds/g5.jpg','secondary'),
(NULL,4,'/static/img/grounds/g6.jpg','secondary'),

(NULL,5,'/static/img/grounds/g5.jpg','main'),
(NULL,5,'/static/img/grounds/g2.jpg','secondary'),
(NULL,5,'/static/img/grounds/g3.jpg','secondary'),
(NULL,5,'/static/img/grounds/g4.jpg','secondary'),
(NULL,5,'/static/img/grounds/g1.jpg','secondary'),
(NULL,5,'/static/img/grounds/g6.jpg','secondary'),

(NULL,6,'/static/img/grounds/g6.jpg','main'),
(NULL,6,'/static/img/grounds/g2.jpg','secondary'),
(NULL,6,'/static/img/grounds/g3.jpg','secondary'),
(NULL,6,'/static/img/grounds/g4.jpg','secondary'),
(NULL,6,'/static/img/grounds/g5.jpg','secondary'),
(NULL,6,'/static/img/grounds/g1.jpg','secondary'),

(NULL,7,'/static/img/grounds/g1.jpg','main'),
(NULL,7,'/static/img/grounds/g2.jpg','secondary'),
(NULL,7,'/static/img/grounds/g3.jpg','secondary'),
(NULL,7,'/static/img/grounds/g4.jpg','secondary'),
(NULL,7,'/static/img/grounds/g5.jpg','secondary'),
(NULL,7,'/static/img/grounds/g6.jpg','secondary'),

(NULL,8,'/static/img/grounds/g2.jpg','main'),
(NULL,8,'/static/img/grounds/g1.jpg','secondary'),
(NULL,8,'/static/img/grounds/g3.jpg','secondary'),
(NULL,8,'/static/img/grounds/g4.jpg','secondary'),
(NULL,8,'/static/img/grounds/g5.jpg','secondary'),
(NULL,8,'/static/img/grounds/g6.jpg','secondary'),

(NULL,9,'/static/img/grounds/g3.jpg','main'),
(NULL,9,'/static/img/grounds/g2.jpg','secondary'),
(NULL,9,'/static/img/grounds/g1.jpg','secondary'),
(NULL,9,'/static/img/grounds/g4.jpg','secondary'),
(NULL,9,'/static/img/grounds/g5.jpg','secondary'),
(NULL,9,'/static/img/grounds/g6.jpg','secondary'),

(NULL,10,'/static/img/grounds/g4.jpg','main'),
(NULL,10,'/static/img/grounds/g2.jpg','secondary'),
(NULL,10,'/static/img/grounds/g3.jpg','secondary'),
(NULL,10,'/static/img/grounds/g1.jpg','secondary'),
(NULL,10,'/static/img/grounds/g5.jpg','secondary'),
(NULL,10,'/static/img/grounds/g6.jpg','secondary'),

(NULL,11,'/static/img/grounds/g5.jpg','main'),
(NULL,11,'/static/img/grounds/g2.jpg','secondary'),
(NULL,11,'/static/img/grounds/g3.jpg','secondary'),
(NULL,11,'/static/img/grounds/g4.jpg','secondary'),
(NULL,11,'/static/img/grounds/g1.jpg','secondary'),
(NULL,11,'/static/img/grounds/g6.jpg','secondary'),

(NULL,12,'/static/img/grounds/g6.jpg','main'),
(NULL,12,'/static/img/grounds/g2.jpg','secondary'),
(NULL,12,'/static/img/grounds/g3.jpg','secondary'),
(NULL,12,'/static/img/grounds/g4.jpg','secondary'),
(NULL,12,'/static/img/grounds/g5.jpg','secondary'),
(NULL,12,'/static/img/grounds/g1.jpg','secondary'),

(NULL,13,'/static/img/grounds/g1.jpg','main'),
(NULL,13,'/static/img/grounds/g2.jpg','secondary'),
(NULL,13,'/static/img/grounds/g3.jpg','secondary'),
(NULL,13,'/static/img/grounds/g4.jpg','secondary'),
(NULL,13,'/static/img/grounds/g5.jpg','secondary'),
(NULL,13,'/static/img/grounds/g6.jpg','secondary'),

(NULL,14,'/static/img/grounds/g2.jpg','main'),
(NULL,14,'/static/img/grounds/g1.jpg','secondary'),
(NULL,14,'/static/img/grounds/g3.jpg','secondary'),
(NULL,14,'/static/img/grounds/g4.jpg','secondary'),
(NULL,14,'/static/img/grounds/g5.jpg','secondary'),
(NULL,14,'/static/img/grounds/g6.jpg','secondary'),

(NULL,15,'/static/img/grounds/g3.jpg','main'),
(NULL,15,'/static/img/grounds/g2.jpg','secondary'),
(NULL,15,'/static/img/grounds/g1.jpg','secondary'),
(NULL,15,'/static/img/grounds/g4.jpg','secondary'),
(NULL,15,'/static/img/grounds/g5.jpg','secondary'),
(NULL,15,'/static/img/grounds/g6.jpg','secondary');

