INSERT INTO `mydb`.`images_houses_rent`
(`image_id`,`obj_id`,`path`,`status`)
VALUES
(NULL,1,'/static/img/houses/h1.jpg','main'),
(NULL,1,'/static/img/houses/h2.jpg','secondary'),
(NULL,1,'/static/img/houses/h3.jpg','secondary'),
(NULL,1,'/static/img/houses/h4.jpg','secondary'),
(NULL,1,'/static/img/houses/h5.jpg','secondary'),
(NULL,1,'/static/img/houses/h6.jpg','secondary'),

(NULL,2,'/static/img/houses/h2.jpg','main'),
(NULL,2,'/static/img/houses/h1.jpg','secondary'),
(NULL,2,'/static/img/houses/h3.jpg','secondary'),
(NULL,2,'/static/img/houses/h4.jpg','secondary'),
(NULL,2,'/static/img/houses/h5.jpg','secondary'),
(NULL,2,'/static/img/houses/h6.jpg','secondary'),

(NULL,3,'/static/img/houses/h3.jpg','main'),
(NULL,3,'/static/img/houses/h2.jpg','secondary'),
(NULL,3,'/static/img/houses/h1.jpg','secondary'),
(NULL,3,'/static/img/houses/h4.jpg','secondary'),
(NULL,3,'/static/img/houses/h5.jpg','secondary'),
(NULL,3,'/static/img/houses/h6.jpg','secondary'),

(NULL,4,'/static/img/houses/h4.jpg','main'),
(NULL,4,'/static/img/houses/h2.jpg','secondary'),
(NULL,4,'/static/img/houses/h3.jpg','secondary'),
(NULL,4,'/static/img/houses/h1.jpg','secondary'),
(NULL,4,'/static/img/houses/h5.jpg','secondary'),
(NULL,4,'/static/img/houses/h6.jpg','secondary'),

(NULL,5,'/static/img/houses/h5.jpg','main'),
(NULL,5,'/static/img/houses/h2.jpg','secondary'),
(NULL,5,'/static/img/houses/h3.jpg','secondary'),
(NULL,5,'/static/img/houses/h4.jpg','secondary'),
(NULL,5,'/static/img/houses/h1.jpg','secondary'),
(NULL,5,'/static/img/houses/h6.jpg','secondary'),

(NULL,6,'/static/img/houses/h6.jpg','main'),
(NULL,6,'/static/img/houses/h2.jpg','secondary'),
(NULL,6,'/static/img/houses/h3.jpg','secondary'),
(NULL,6,'/static/img/houses/h4.jpg','secondary'),
(NULL,6,'/static/img/houses/h5.jpg','secondary'),
(NULL,6,'/static/img/houses/h1.jpg','secondary'),

(NULL,7,'/static/img/houses/h1.jpg','main'),
(NULL,7,'/static/img/houses/h2.jpg','secondary'),
(NULL,7,'/static/img/houses/h3.jpg','secondary'),
(NULL,7,'/static/img/houses/h4.jpg','secondary'),
(NULL,7,'/static/img/houses/h5.jpg','secondary'),
(NULL,7,'/static/img/houses/h6.jpg','secondary'),

(NULL,8,'/static/img/houses/h2.jpg','main'),
(NULL,8,'/static/img/houses/h1.jpg','secondary'),
(NULL,8,'/static/img/houses/h3.jpg','secondary'),
(NULL,8,'/static/img/houses/h4.jpg','secondary'),
(NULL,8,'/static/img/houses/h5.jpg','secondary'),
(NULL,8,'/static/img/houses/h6.jpg','secondary'),

(NULL,9,'/static/img/houses/h3.jpg','main'),
(NULL,9,'/static/img/houses/h2.jpg','secondary'),
(NULL,9,'/static/img/houses/h1.jpg','secondary'),
(NULL,9,'/static/img/houses/h4.jpg','secondary'),
(NULL,9,'/static/img/houses/h5.jpg','secondary'),
(NULL,9,'/static/img/houses/h6.jpg','secondary'),

(NULL,10,'/static/img/houses/h4.jpg','main'),
(NULL,10,'/static/img/houses/h2.jpg','secondary'),
(NULL,10,'/static/img/houses/h3.jpg','secondary'),
(NULL,10,'/static/img/houses/h1.jpg','secondary'),
(NULL,10,'/static/img/houses/h5.jpg','secondary'),
(NULL,10,'/static/img/houses/h6.jpg','secondary');
