INSERT INTO `mydb`.`images_flats_rent`
(`image_id`,`obj_id`,`path`,`status`)
VALUES
(NULL,1,'/static/img/flats/flat11.jpg','main'),
(NULL,1,'/static/img/flats/flat12.jpg','secondary'),
(NULL,1,'/static/img/flats/flat13.jpg','secondary'),
(NULL,1,'/static/img/flats/flat14.jpg','secondary'),
(NULL,1,'/static/img/flats/flat15.jpg','secondary'),
(NULL,1,'/static/img/flats/flat16.jpg','secondary'),

(NULL,2,'/static/img/flats/flat12.jpg','main'),
(NULL,2,'/static/img/flats/flat11.jpg','secondary'),
(NULL,2,'/static/img/flats/flat13.jpg','secondary'),
(NULL,2,'/static/img/flats/flat14.jpg','secondary'),
(NULL,2,'/static/img/flats/flat15.jpg','secondary'),
(NULL,2,'/static/img/flats/flat16.jpg','secondary'),

(NULL,3,'/static/img/flats/flat13.jpg','main'),
(NULL,3,'/static/img/flats/flat12.jpg','secondary'),
(NULL,3,'/static/img/flats/flat11.jpg','secondary'),
(NULL,3,'/static/img/flats/flat14.jpg','secondary'),
(NULL,3,'/static/img/flats/flat15.jpg','secondary'),
(NULL,3,'/static/img/flats/flat16.jpg','secondary'),

(NULL,4,'/static/img/flats/flat14.jpg','main'),
(NULL,4,'/static/img/flats/flat12.jpg','secondary'),
(NULL,4,'/static/img/flats/flat13.jpg','secondary'),
(NULL,4,'/static/img/flats/flat11.jpg','secondary'),
(NULL,4,'/static/img/flats/flat15.jpg','secondary'),
(NULL,4,'/static/img/flats/flat16.jpg','secondary'),

(NULL,5,'/static/img/flats/flat15.jpg','main'),
(NULL,5,'/static/img/flats/flat12.jpg','secondary'),
(NULL,5,'/static/img/flats/flat13.jpg','secondary'),
(NULL,5,'/static/img/flats/flat14.jpg','secondary'),
(NULL,5,'/static/img/flats/flat11.jpg','secondary'),
(NULL,5,'/static/img/flats/flat16.jpg','secondary'),

(NULL,6,'/static/img/flats/flat16.jpg','main'),
(NULL,6,'/static/img/flats/flat12.jpg','secondary'),
(NULL,6,'/static/img/flats/flat13.jpg','secondary'),
(NULL,6,'/static/img/flats/flat14.jpg','secondary'),
(NULL,6,'/static/img/flats/flat15.jpg','secondary'),
(NULL,6,'/static/img/flats/flat11.jpg','secondary'),

(NULL,7,'/static/img/flats/flat11.jpg','main'),
(NULL,7,'/static/img/flats/flat12.jpg','secondary'),
(NULL,7,'/static/img/flats/flat13.jpg','secondary'),
(NULL,7,'/static/img/flats/flat14.jpg','secondary'),
(NULL,7,'/static/img/flats/flat15.jpg','secondary'),
(NULL,7,'/static/img/flats/flat16.jpg','secondary'),

(NULL,8,'/static/img/flats/flat12.jpg','main'),
(NULL,8,'/static/img/flats/flat11.jpg','secondary'),
(NULL,8,'/static/img/flats/flat13.jpg','secondary'),
(NULL,8,'/static/img/flats/flat14.jpg','secondary'),
(NULL,8,'/static/img/flats/flat15.jpg','secondary'),
(NULL,8,'/static/img/flats/flat16.jpg','secondary'),

(NULL,9,'/static/img/flats/flat13.jpg','main'),
(NULL,9,'/static/img/flats/flat12.jpg','secondary'),
(NULL,9,'/static/img/flats/flat11.jpg','secondary'),
(NULL,9,'/static/img/flats/flat14.jpg','secondary'),
(NULL,9,'/static/img/flats/flat15.jpg','secondary'),
(NULL,9,'/static/img/flats/flat16.jpg','secondary'),

(NULL,10,'/static/img/flats/flat14.jpg','main'),
(NULL,10,'/static/img/flats/flat12.jpg','secondary'),
(NULL,10,'/static/img/flats/flat13.jpg','secondary'),
(NULL,10,'/static/img/flats/flat11.jpg','secondary'),
(NULL,10,'/static/img/flats/flat15.jpg','secondary'),
(NULL,10,'/static/img/flats/flat16.jpg','secondary'),

(NULL,11,'/static/img/flats/flat15.jpg','main'),
(NULL,11,'/static/img/flats/flat12.jpg','secondary'),
(NULL,11,'/static/img/flats/flat13.jpg','secondary'),
(NULL,11,'/static/img/flats/flat14.jpg','secondary'),
(NULL,11,'/static/img/flats/flat11.jpg','secondary'),
(NULL,11,'/static/img/flats/flat16.jpg','secondary'),

(NULL,12,'/static/img/flats/flat16.jpg','main'),
(NULL,12,'/static/img/flats/flat12.jpg','secondary'),
(NULL,12,'/static/img/flats/flat13.jpg','secondary'),
(NULL,12,'/static/img/flats/flat14.jpg','secondary'),
(NULL,12,'/static/img/flats/flat15.jpg','secondary'),
(NULL,12,'/static/img/flats/flat11.jpg','secondary'),

(NULL,13,'/static/img/flats/flat11.jpg','main'),
(NULL,13,'/static/img/flats/flat12.jpg','secondary'),
(NULL,13,'/static/img/flats/flat13.jpg','secondary'),
(NULL,13,'/static/img/flats/flat14.jpg','secondary'),
(NULL,13,'/static/img/flats/flat15.jpg','secondary'),
(NULL,13,'/static/img/flats/flat16.jpg','secondary'),

(NULL,14,'/static/img/flats/flat12.jpg','main'),
(NULL,14,'/static/img/flats/flat11.jpg','secondary'),
(NULL,14,'/static/img/flats/flat13.jpg','secondary'),
(NULL,14,'/static/img/flats/flat14.jpg','secondary'),
(NULL,14,'/static/img/flats/flat15.jpg','secondary'),
(NULL,14,'/static/img/flats/flat16.jpg','secondary'),

(NULL,15,'/static/img/flats/flat13.jpg','main'),
(NULL,15,'/static/img/flats/flat12.jpg','secondary'),
(NULL,15,'/static/img/flats/flat11.jpg','secondary'),
(NULL,15,'/static/img/flats/flat14.jpg','secondary'),
(NULL,15,'/static/img/flats/flat15.jpg','secondary'),
(NULL,15,'/static/img/flats/flat16.jpg','secondary'),

(NULL,16,'/static/img/flats/flat14.jpg','main'),
(NULL,16,'/static/img/flats/flat12.jpg','secondary'),
(NULL,16,'/static/img/flats/flat13.jpg','secondary'),
(NULL,16,'/static/img/flats/flat11.jpg','secondary'),
(NULL,16,'/static/img/flats/flat15.jpg','secondary'),
(NULL,16,'/static/img/flats/flat16.jpg','secondary'),

(NULL,17,'/static/img/flats/flat15.jpg','main'),
(NULL,17,'/static/img/flats/flat12.jpg','secondary'),
(NULL,17,'/static/img/flats/flat13.jpg','secondary'),
(NULL,17,'/static/img/flats/flat14.jpg','secondary'),
(NULL,17,'/static/img/flats/flat11.jpg','secondary'),
(NULL,17,'/static/img/flats/flat16.jpg','secondary'),

(NULL,18,'/static/img/flats/flat16.jpg','main'),
(NULL,18,'/static/img/flats/flat12.jpg','secondary'),
(NULL,18,'/static/img/flats/flat13.jpg','secondary'),
(NULL,18,'/static/img/flats/flat14.jpg','secondary'),
(NULL,18,'/static/img/flats/flat15.jpg','secondary'),
(NULL,18,'/static/img/flats/flat11.jpg','secondary'),

(NULL,19,'/static/img/flats/flat11.jpg','main'),
(NULL,19,'/static/img/flats/flat12.jpg','secondary'),
(NULL,19,'/static/img/flats/flat13.jpg','secondary'),
(NULL,19,'/static/img/flats/flat14.jpg','secondary'),
(NULL,19,'/static/img/flats/flat15.jpg','secondary'),
(NULL,19,'/static/img/flats/flat16.jpg','secondary'),

(NULL,20,'/static/img/flats/flat12.jpg','main'),
(NULL,20,'/static/img/flats/flat11.jpg','secondary'),
(NULL,20,'/static/img/flats/flat13.jpg','secondary'),
(NULL,20,'/static/img/flats/flat14.jpg','secondary'),
(NULL,20,'/static/img/flats/flat15.jpg','secondary'),
(NULL,20,'/static/img/flats/flat16.jpg','secondary'),

(NULL,21,'/static/img/flats/flat13.jpg','main'),
(NULL,21,'/static/img/flats/flat12.jpg','secondary'),
(NULL,21,'/static/img/flats/flat11.jpg','secondary'),
(NULL,21,'/static/img/flats/flat14.jpg','secondary'),
(NULL,21,'/static/img/flats/flat15.jpg','secondary'),
(NULL,21,'/static/img/flats/flat16.jpg','secondary'),

(NULL,22,'/static/img/flats/flat14.jpg','main'),
(NULL,22,'/static/img/flats/flat12.jpg','secondary'),
(NULL,22,'/static/img/flats/flat13.jpg','secondary'),
(NULL,22,'/static/img/flats/flat14.jpg','secondary'),
(NULL,22,'/static/img/flats/flat15.jpg','secondary'),
(NULL,22,'/static/img/flats/flat16.jpg','secondary'),

(NULL,23,'/static/img/flats/flat15.jpg','main'),
(NULL,23,'/static/img/flats/flat12.jpg','secondary'),
(NULL,23,'/static/img/flats/flat13.jpg','secondary'),
(NULL,23,'/static/img/flats/flat14.jpg','secondary'),
(NULL,23,'/static/img/flats/flat11.jpg','secondary'),
(NULL,23,'/static/img/flats/flat16.jpg','secondary'),

(NULL,24,'/static/img/flats/flat16.jpg','main'),
(NULL,24,'/static/img/flats/flat12.jpg','secondary'),
(NULL,24,'/static/img/flats/flat13.jpg','secondary'),
(NULL,24,'/static/img/flats/flat14.jpg','secondary'),
(NULL,24,'/static/img/flats/flat15.jpg','secondary'),
(NULL,24,'/static/img/flats/flat11.jpg','secondary'),

(NULL,25,'/static/img/flats/flat11.jpg','main'),
(NULL,25,'/static/img/flats/flat12.jpg','secondary'),
(NULL,25,'/static/img/flats/flat13.jpg','secondary'),
(NULL,25,'/static/img/flats/flat14.jpg','secondary'),
(NULL,25,'/static/img/flats/flat15.jpg','secondary'),
(NULL,25,'/static/img/flats/flat16.jpg','secondary'),

(NULL,26,'/static/img/flats/flat12.jpg','main'),
(NULL,26,'/static/img/flats/flat11.jpg','secondary'),
(NULL,26,'/static/img/flats/flat13.jpg','secondary'),
(NULL,26,'/static/img/flats/flat14.jpg','secondary'),
(NULL,26,'/static/img/flats/flat15.jpg','secondary'),
(NULL,26,'/static/img/flats/flat16.jpg','secondary'),

(NULL,27,'/static/img/flats/flat13.jpg','main'),
(NULL,27,'/static/img/flats/flat12.jpg','secondary'),
(NULL,27,'/static/img/flats/flat11.jpg','secondary'),
(NULL,27,'/static/img/flats/flat14.jpg','secondary'),
(NULL,27,'/static/img/flats/flat15.jpg','secondary'),
(NULL,27,'/static/img/flats/flat16.jpg','secondary'),


(NULL,28,'/static/img/flats/flat14.jpg','main'),
(NULL,28,'/static/img/flats/flat12.jpg','secondary'),
(NULL,28,'/static/img/flats/flat13.jpg','secondary'),
(NULL,28,'/static/img/flats/flat11.jpg','secondary'),
(NULL,28,'/static/img/flats/flat15.jpg','secondary'),
(NULL,28,'/static/img/flats/flat16.jpg','secondary'),

(NULL,29,'/static/img/flats/flat15.jpg','main'),
(NULL,29,'/static/img/flats/flat12.jpg','secondary'),
(NULL,29,'/static/img/flats/flat13.jpg','secondary'),
(NULL,29,'/static/img/flats/flat14.jpg','secondary'),
(NULL,29,'/static/img/flats/flat11.jpg','secondary'),
(NULL,29,'/static/img/flats/flat16.jpg','secondary'),

(NULL,30,'/static/img/flats/flat16.jpg','main'),
(NULL,30,'/static/img/flats/flat12.jpg','secondary'),
(NULL,30,'/static/img/flats/flat13.jpg','secondary'),
(NULL,30,'/static/img/flats/flat14.jpg','secondary'),
(NULL,30,'/static/img/flats/flat15.jpg','secondary'),
(NULL,30,'/static/img/flats/flat11.jpg','secondary');



