DROP TABLE IF EXISTS `testnodedb`.`houses_sell` ;
CREATE TABLE IF NOT EXISTS `testnodedb`.`houses_sell` (
  `obj_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_object_number` VARCHAR(45) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` VARCHAR(45) NULL,
  `objt_price` VARCHAR(45) NULL,
  `obj_floors_number` VARCHAR(45) NULL,
  `obj_rooms_number` VARCHAR(45) NULL,
  `obj_year_build` VARCHAR(45) NULL,
  `obj_sq_common` VARCHAR(45) NULL,
  `obj_sq_living` VARCHAR(45) NULL,
  `obj_sq_kitchen` VARCHAR(45) NULL,
  `obj_status` VARCHAR(45) NULL,
  `obj_from` VARCHAR(45) NULL,
  `map_coord_x` VARCHAR(45) NULL,
  `map_coord_y` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`obj_id`))
ENGINE = MyISAM;