CREATE TABLE IF NOT EXISTS `testnodedb`.`flats_rent` (
	`obj_id` INT(30) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	`user_id` INT(30) NULL,
	`obj_type` VARCHAR(45) NULL,
	`addr_city` VARCHAR(45) NULL,
	`addr_street` VARCHAR(45) NULL,
	`addr_obj_num` VARCHAR(5) NULL,
	`addr_metro` VARCHAR(45) NULL,
	`obj_name` VARCHAR(45) NULL,
	`obj_description` TEXT(300) NULL,
	`obj_price` INT(30) NULL,
	`obj_floor` INT(3) NULL,
	`obj_floors_num` INT(3) NULL,
	`obj_rooms_num` INT(3) NULL,
	`obj_year_build` DATE NULL,
	`obj_sq_common` INT(10) NULL,
	`obj_sq_living` INT(10) NULL,
	`obj_sq_kitchen` INT(10) NULL,
	`obj_status` VARCHAR(10) NULL,
	`obj_from` VARCHAR(10) NULL,
	`obj_reservation` TINYINT(1) NULL,
	`map_coord_x` VARCHAR(45) NULL,
	`map_coord_y` VARCHAR(45) NULL,
	`date` DATE NULL,
	`fac_aircond` TINYINT(1) NULL,
	`fac_dishwasher` TINYINT(1) NULL,
	`fac_fridge` TINYINT(1) NULL,
	`fac_furniture` TINYINT(1) NULL,
	`fac_microwave` TINYINT(1) NULL,
	`fac_tel` TINYINT(1) NULL,
	`fac_tv` TINYINT(1) NULL,
	`fac_washer` TINYINT(1) NULL,
	`fac_wifi` TINYINT(1) NULL,
	`rent_time` VARCHAR(45) NULL,
	`obj_guests_num` INT(4) NULL)
ENGINE = MyISAM;



CREATE TABLE IF NOT EXISTS `mydb`.`flats_rent` (
  `obj_id` INT(30) NOT NULL,
  `user_id` INT(30) NULL,
  `obj_type` VARCHAR(45) NULL,
  `addr_city` VARCHAR(45) NULL,
  `addr_street` VARCHAR(45) NULL,
  `addr_obj_num` VARCHAR(5) NULL,
  `addr_metro` VARCHAR(45) NULL,
  `obj_name` VARCHAR(45) NULL,
  `obj_description` TEXT(300) NULL,
  `obj_price` INT(30) NULL,
  `obj_floor` INT(3) NULL,
  `obj_floors_num` INT(3) NULL,
  `obj_rooms_num` INT(3) NULL,
  `obj_year_build` DATE NULL,
  `obj_sq_common` INT(10) NULL,
  `obj_sq_living` INT(10) NULL,
  `obj_sq_kitchen` INT(10) NULL,
  `obj_status` VARCHAR(10) NULL,
  `obj_from` VARCHAR(10) NULL,
  `obj_reservation` TINYINT(1) NULL,
  `map_coord_x` VARCHAR(45) NULL,
  `map_coord_y` VARCHAR(45) NULL,
  `date` DATE NULL,
  `fac_aircond` TINYINT(1) NULL,
  `fac_dishwasher` TINYINT(1) NULL,
  `fac_fridge` TINYINT(1) NULL,
  `fac_furniture` TINYINT(1) NULL,
  `fac_microwave` TINYINT(1) NULL,
  `fac_tel` TINYINT(1) NULL,
  `fac_tv` TINYINT(1) NULL,
  `fac_washer` TINYINT(1) NULL,
  `fac_wifi` TINYINT(1) NULL,
  `rent_time` VARCHAR(45) NULL,
  `obj_guests_num` INT(4) NULL)
ENGINE = InnoDB;